---
functional:
  - Пользователи должны иметь возможность зарегистрироваться на сайте различными способами
  - Пользователи должны иметь возможность приглашать игроков с помощью ссылки 
  - Пользователи должны иметь возмодность играть друг с другом и видеть написание кода соперника 
  - Пользователи должны иметь возможность играть с ботом 
  - Пользователи должны иметь возможность просматривать рейтинги 
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Фунционал мобильной версии не должен отличаться 
  - Сайт должен быть адаптивным
  - Сайт должен сохронять политику конфиденцальности
