---
functional:
  - Пользователи должны иметь возможность зарегистрироваться на сайте различными способами
  - Пользователи должны иметь возможность приглашать игроков с помощью ссылки 
  - Пользователи должны иметь возмодность играть друг с другом и видеть написание кода соперника 
  - Пользователи должны иметь возможность играть с ботом 
  - Пользователи должны иметь возможность просматривать рейтинги 
  - Пользователь должен иметь возмоность просматривать турниры и участвовать в них
  - Пользователь должен иметь доступ к телеграмм каналу 
  - Пользователь должен иметь возможность просматривать исходный код 
  - Пользователь должен иметь возможность просматривать задачи и создавать новые 
  - Пользователь должен иметь доступ к настройкам 
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Фунционал мобильной версии не должен отличаться 
  - Сайт должен быть адаптивным
  - Сайт должен сохронять политику конфиденцальности
